from __future__ import annotations

from abc import abstractmethod

from Core.NumberSystem.Domain import Domain


class Set(Domain):

    def __init__(self, name: str | None = None):
        super().__init__(name if name is not None else type(self).__name__)

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, other: object) -> bool: ...

    def __contains__(self, item: float) -> bool: ...

    def union(self, other: Set) -> Set: ...

    def intersect(self, other: Set) -> Set: ...

    def complement(self) -> Set: ...

    def without(self, other: Set) -> Set: ...

    @abstractmethod
    def contains(self, element: float) -> bool: ...

    def is_empty(self) -> bool: ...

    def is_singleton(self) -> bool: ...

    def copy(self) -> Set: ...

    def get_singleton_element(self) -> float: ...
