from __future__ import annotations


class Set:

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, other: object) -> bool: ...

    def __contains__(self, item: float) -> bool: ...

    def union(self, other: Set) -> Set: ...

    def intersect(self, other: Set) -> Set: ...

    def complement(self) -> Set: ...

    def without(self, other: Set) -> Set: ...

    def contains(self, element: float) -> bool: ...

    def is_empty(self) -> bool: ...

    def is_singleton(self) -> bool: ...

    def copy(self) -> Set: ...

    def get_singleton_element(self) -> float: ...
